### ISSUE TITLE
Alternatives to TOML description

### ISSUE THREAD

**Issue by kvark** [redox-os/orbgame#8]
Describing the whole game in text format is kinda neat, but the choice of TOML appears to be a limiting factor: that format doesn't like rich types and deeply nested structures. I assume that to be the reason to have multiple smaller TOML files in the "adventure" folder.

Please consider [RON](https://github.com/ron-rs/ron) for a cleaner alternative.

**Comment by FloVanGH** [comment]
Thank you for this hint. I split it in multiple smaller files to have the ability to reference resources like a sprite on different object and to have a cleaner structure. But RON is very interesting, it reminds me a little bit on Qml. It could have some advantages for orbgame. I‘ll check it. It could be also interesting for declarative description of user interfaces.

**Comment by FloVanGH** [comment]
Thank you. I really like it. I complete replace TOML with RON.
